---
- name: Include global splunk variables
  include_vars: /opt/ansible/group_vars/splunk.yml

- name: Include vault
  include_vars: /opt/ansible/content/secrets/main.yml

- name: Deploy splunk-shf role
  include_tasks: "{{ item }}"
  loop:
    - firewalld.yml
    - disable_webserver.yml
    - storage_perms.yml