## RHEL-07-020100
- name: Ensure kernel module 'usb-storage' is disabled
  lineinfile:
    create: yes
    dest: "/etc/modprobe.d/usb-storage.conf"
    regexp: 'usb-storage'
    line: "install usb-storage /bin/true"
  tags:
  - RHEL-07-020100
  when:  # Bare-metal/VM task, not applicable for containers
    - (ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker")
