---
- name: Changes splunk service account password
  hosts: ALL_SH
  become: true
  gather_facts: false
  vars_files:
    - /opt/ansible/content/secrets/main.yml

  tasks:
    - name: Check if splunk is running
      shell: "/opt/splunk/bin/splunk status"
      become_user: splunk
      register: splunk_status

    - name: Fail if splunk is running
      fail:
        msg: "Splunk is running, refusing to proceed..."
      when: '"splunk helpers are running" in splunk_status.stdout' 