---
- name: Checking splunk's owner
  hosts: ALL_SPLUNK_ENTERPRISE
  become: true
  gather_facts: false

  tasks:
    - name: Find splunk parent process
      shell: ps -few | grep -i "splunkd -p 8089 start \|splunkd -p 8089 restart" | grep -v "grep" | head -n 1 | awk '{print $1}'
      register: splunk_owner
      changed_when: "'NONSENSE' in splunk_owner"
      failed_when: "'splunk' not in splunk_owner.stdout"
      ignore_errors: true

    - name: Report non-splunk user, if needed
      debug:
        msg: Splunk is running as {{ splunk_owner.stdout }}!
      when: splunk_owner.stdout != "splunk"